import Footer from './components/Footer/Footer';
import Navbar from './components/Navbar/Navbar';
import './globals.css';


export const metadata = {
  title: 'Ei Courses',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
